name: jain-digitizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - rich
  - pyinstaller>=6.0.0
  - pyinstaller-hooks-contrib
  - pip:
      - google-genai
      - streamlit
      - streamlit-quill
      - pyside6
